# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QQ_Message.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'QQ_Message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10QQ_Message.proto\"-\n\x07Message\x12\"\n\x08messages\x18\xe0\xbe\x02 \x03(\x0b\x32\x0e.SingleMessage\"\xee\x05\n\rSingleMessage\x12\x13\n\tmessageId\x18\xc9\xdf\x02 \x01(\x04\x12\x15\n\x0bmessageType\x18\xca\xdf\x02 \x01(\r\x12\x12\n\x08senderId\x18\xd4\xb8\x02 \x01(\t\x12\x14\n\nreceiverId\x18\xd5\xb8\x02 \x01(\t\x12\x15\n\x0bmessageText\x18\xad\xe0\x02 \x01(\t\x12\x12\n\x08\x66ileName\x18\xda\xe2\x02 \x01(\t\x12\x12\n\x08\x66ileSize\x18\xdd\xe2\x02 \x01(\x04\x12\x1b\n\x11sendTimestampFile\x18\xc1\xe3\x02 \x01(\x04\x12\x15\n\x0bimageUrlLow\x18\xea\xe5\x02 \x01(\t\x12\x16\n\x0cimageUrlHigh\x18\xeb\xe5\x02 \x01(\t\x12\x18\n\x0eimageUrlOrigin\x18\xec\xe5\x02 \x01(\t\x12\x13\n\timageText\x18\xf7\xe5\x02 \x01(\t\x12\x13\n\tsenderUid\x18\xab\xf2\x02 \x01(\r\x12\x17\n\rsendTimestamp\x18\xac\xf2\x02 \x01(\r\x12\x15\n\x0breceiverUid\x18\xb3\xf2\x02 \x01(\r\x12&\n\x0creplyMessage\x18\xbf\xf2\x02 \x01(\x0b\x32\x0e.SingleMessage\x12\x11\n\x07\x65mojiId\x18\xf1\xf3\x02 \x01(\r\x12\x13\n\temojiText\x18\xf2\xf3\x02 \x01(\t\x12\x1c\n\x12\x61pplicationMessage\x18\x9d\xf6\x02 \x01(\t\x12\x18\n\x0e\x63\x61llStatusText\x18\x99\xf8\x02 \x01(\t\x12\x12\n\x08\x63\x61llText\x18\x9d\xf8\x02 \x01(\t\x12!\n\tfeedTitle\x18\xaf\xf8\x02 \x01(\x0b\x32\x0c.FeedMessage\x12#\n\x0b\x66\x65\x65\x64\x43ontent\x18\xb0\xf8\x02 \x01(\x0b\x32\x0c.FeedMessage\x12\x11\n\x07\x66\x65\x65\x64Url\x18\xb4\xf8\x02 \x01(\t\x12\x15\n\x0b\x66\x65\x65\x64LogoUrl\x18\xb5\xf8\x02 \x01(\t\x12\x1a\n\x10\x66\x65\x65\x64PublisherUid\x18\xb6\xf8\x02 \x01(\r\x12\x16\n\x0c\x66\x65\x65\x64JumpInfo\x18\xb7\xf8\x02 \x01(\t\x12\x19\n\x0f\x66\x65\x65\x64PublisherId\x18\xbc\xf8\x02 \x01(\t\x12\x14\n\nnoticeInfo\x18\xd6\xf8\x02 \x01(\t\x12\x15\n\x0bnoticeInfo2\x18\x8f\xf9\x02 \x01(\t\"\x1d\n\x0b\x46\x65\x65\x64Message\x12\x0e\n\x04text\x18\xb2\xf8\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QQ_Message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=20
  _globals['_MESSAGE']._serialized_end=65
  _globals['_SINGLEMESSAGE']._serialized_start=68
  _globals['_SINGLEMESSAGE']._serialized_end=818
  _globals['_FEEDMESSAGE']._serialized_start=820
  _globals['_FEEDMESSAGE']._serialized_end=849
# @@protoc_insertion_point(module_scope)

